[workspace]
resolver = "2"
members = ["common", "server", "client"]

[workspace.dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "dynamic_linking",
] }
bevy_common_assets = { version = "0.11", features = ["ron"] }
leafwing-input-manager = "0.15"
lightyear = { git = "https://github.com/cBournhonesque/lightyear.git", features = [
    "leafwing",
] }
rand = "0.8"
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
