cargo-features = ["codegen-backend"]

[package]
name = "robot-rumble-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_common_assets = { version = "0.12", features = ["ron"] }
bevy_asset_loader = { version = "0.22", features = ["2d"] }
bevy_ggrs = { version = "0.17", features = ["wasm-bindgen"] }
bevy_matchbox = { version = "0.11", features = ["ggrs"] }
bevy_embedded_assets = "0.12.0"
bevy-inspector-egui = "0.29"
leafwing-input-manager = "0.16"
rand_xoshiro = "0.7.0"
rand = "0.9.0"
ron = "0.8"
getrandom = { version = "0.3", features = ["wasm_js"] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5.32", features = ["derive"] }

[dependencies.bevy]
version = "0.15"
features = [
  "multi_threaded",
  "bevy_asset",
  "bevy_audio",
  "bevy_gilrs",
  "bevy_winit",
  "bevy_render",
  "bevy_sprite",
  "bevy_ui",
  "default_font",

  "png",
  "vorbis",

  "x11",
  "wayland",
  "webgl2",

  "asset_processor",
]

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
codegen-backend = "cranelift"

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "fat"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
strip = "symbols"
panic = 'abort'
