# WASM
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

# FCT: Mold (for Linux)
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# FCT: LDD (for Windows)
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

# FCT: Cranelift
[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
