name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  # Wait for bevy to adopt encase:0.11.1 to benefit https://github.com/teoxoy/encase/pull/96
  RUSTFLAGS: "-A dead-code"

jobs:
  check:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install g++ pkg-config mold libx11-dev libwayland-dev libasound2-dev libudev-dev
    - name: Setup rust toolchain
      run: |
        rustup update ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
    - name: Setup codegen-backend
      run: rustup component add rustc-codegen-cranelift-preview --toolchain ${{ matrix.toolchain }}
    - name: Install lint components
      run: |
        rustup component add rustfmt --toolchain ${{ matrix.toolchain }}
        rustup component add clippy --toolchain ${{ matrix.toolchain }}
    - name: Print Rust and Clippy versions
      run: |
        rustc --version
        cargo clippy --version
    - name: Lint (rustfmt)
      run: cargo fmt --all --check
    - name: Lint (clippy)
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Test (cargo)
      run: cargo test
