name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install g++ pkg-config mold libx11-dev libwayland-dev libasound2-dev libudev-dev
    - name: Setup rust toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add rustc-codegen-cranelift-preview --toolchain ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
